### ISSUE TITLE
[REQ] Visual Studio Code extension

### ISSUE THREAD

**Issue by DartMen** [campbellC/third-wheel#30]
Nice project!

It would be very nice to have a Visual Studio Code extension eventually.

And support for Remote WSL.

**Comment by campbellC** [comment]
Thanks for making a feature request! I don’t use vscode or Windows so I’m unlikely the best person to make this. What do you envisage the extension would do?

**Comment by DartMen** [comment]
To have easy access to visuals of the requests/responses, like mitmproxy does or network tab in chrome developer tools, something like that would be awesome.

Maybe I can look into it after you have crystalized third-wheel into beta stage.

**Comment by campbellC** [comment]
If I understand correctly, think what you want is a HAR file viewer. These already exist, including an [extension for vscode](https://github.com/craignicol/har-v). So third wheel could be used to produce har files and then you can load them in the har viewer. 

There’s an example har-capture script to produce har files from a session although it’s really just a skeleton and missing a lot of the data you’d need for a complete HAR .

Please reopen if I’ve not understood correctly
