### ISSUE TITLE
Could this be used to write a website blocker?

### ISSUE THREAD

**Issue by vedantroy** [campbellC/third-wheel#32]
Trying to write a Rust version of [Chomper](https://github.com/aniketpanjwani/chomper), not sure if this tool is right for the job?

**Comment by campbellC** [comment]
Hi there. Whilst I’ve never used Chomper, taking a look at the [install script](https://github.com/aniketpanjwani/chomper_installers/blob/master/debian.sh) it seems that it’s based off of mitmproxy. So yes absolutely - third  wheel would be what you need.

**Comment by campbellC** [comment]
[this file](https://github.com/aniketpanjwani/chomper/blob/master/chomper/filter.py) contains the actual blocking logic for Chomper and is what is run by the mitmproxy Script api. Mitmproxy is a separate binary that you can load with a given script whereas third-wheel is a library so the code layout will be slightly different.

If the documentation for third wheel doesn’t make it clear how to go about this please open an issue and I’ll do my best to sort that out.
